pipeline {
    agent any 
    stages {
        stage('Static Analysis') {
            steps {
                echo 'This is Sumit kumar making change in jenkins file' 
            }
        }
        stage('Compile') {
            steps {
                echo 'Compile the source code' 
            }
        }
        stage('Security Check') {
            steps {
                echo 'To make sure changes are visible in jenkins changes ' 
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'It is fun' 
            }
        }
        stage('Run Integration Tests') {
            steps {
                echo 'to learn new technologies' 
            }
        }
        stage('Publish Artifacts') {
            steps {
                echo 'Bye' 
            }
        }
    }
}
